version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    open-pull-requests-limit: 0
    time: "14:00"
  target-branch: "dev"
  labels:
    - "deps"
    - "depbot"
