[package]
name = "rssbot"
version = "2.0.1"
authors = ["iovxw <iovxw@outlook.com>"]
edition = "2024"

[features]
default = ["rustls"]

# enable this to set a subscription limit
hosted-by-iovxw = ["reqwest/trust-dns"]
native-tls = [
    # "tbot/default",
    "teloxide/native-tls",
    "hyper-proxy/default",
    "reqwest/default",
    "reqwest/native-tls-vendored",
    "reqwest/native-tls-alpn",
]
rustls = [
    # "tbot/rustls",
    "teloxide/rustls",
    "hyper-proxy/rustls",
    "reqwest/rustls-tls",
]

[package.metadata.cross.build.env]
passthrough = ["LOCALE"]

[build-dependencies]
ctl10n = "0.2.0"

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
futures = "0.3.31"
tokio = { version = "1.47.1", features = ["full"] }
tokio-util = { version = "0.7.16", features = ["full"] }
tokio-stream = "0.1.17"
thiserror = "2.0.16"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.145"
regex = "1.11.2"
quick-xml = { version = "0.38.3", features = ["encoding", "escape-html"] }
chrono = "0.4"
pinyin = "0.10"
either = "1.15"
atomicwrites = "0.4"
clap = { version = "4.5.47", features = ["derive"] }
teloxide = { version = "0.17.0", features = ["macros", "ctrlc_handler"], default-features = false }

# [dependencies.tbot]
# version = "0.6"
# git = "https://gitlab.com/SnejUgal/tbot.git"
# default-features = false
# features = ["proxy"]

[dependencies.hyper-proxy]
version = "0.9"
default-features = false

[dependencies.reqwest]
version = "0.12"
default-features = false
features = ["gzip", "json"]
