name: Rust

on: [push]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly]
    runs-on: ${{ matrix.os }}

    steps:
#     - uses: hecrj/setup-rust-action@v1
#       with:
#         rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: clippy

    - name: Clippy
      run: cargo clippy --no-deps --all-targets

    - name: Run tests
      run: cargo test -v

  test-locales:
    strategy:
      matrix:
        locale: [zh, en]
    runs-on: ubuntu-latest

    steps:
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - uses: actions/checkout@master
    - name: Check locales
      env:
        LOCALE: ${{ matrix.locale }}
      run: cargo check --verbose
